### ISSUE TITLE
这个报错是java版本问题吗

### ISSUE THREAD

**Issue by bayunhong** [zangcc/Aakian-v1.0#8]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.xjar.reflection.XReflection (file:/D:/Aakian-v1.0-main/Aakian.jar) to field java.net.URLClassLoader.ucp
WARNING: Please consider reporting this to the maintainers of io.xjar.reflection.XReflection
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make public jdk.internal.loader.Resource jdk.internal.loader.URLClassPath.getResource(java.lang.String) accessible: module java.base does not "exports jdk.internal.loader" to unnamed module @43814d18
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
        at io.xjar.reflection.XReflection.method(XReflection.java:35)
        at io.xjar.jar.XJarClassLoader.<init>(XJarClassLoader.java:41)
        at io.xjar.jar.XJarLauncher.launch(XJarLauncher.java:51)
        at io.xjar.jar.XJarLauncher.main(XJarLauncher.java:31)
panic: exit status 1

goroutine 1 [running]:
main.main()
        C:/Users/wang/Desktop/xjar.go:73 +0x670

**Comment by zangcc** [comment]
收到👌🏻，你java是什么版本呢？
